openapi: 3.0.0
info:
    title: Business API
    version: 1.0.0
paths:
    /business/signup:
        post:
            summary: Create a new business
            description: Endpoint to create a new business.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BusinessSignupRequest"
            responses:
                "201":
                    description: Business successfully created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BusinessSignupResponse"
    /business/profile:
        get:
            summary: Get business profile
            description: Endpoint to get the profile of a business.
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BusinessProfileResponse"
    /business/update-password:
        post:
            summary: Update business password
            description: Endpoint to update the password of a business.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UpdatePasswordRequest"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UpdatePasswordResponse"
    /business/verify-password:
        post:
            summary: Verify business password
            description: Endpoint to verify the password of a business.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/VerifyPasswordRequest"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/VerifyPasswordResponse"
    /business/update-email:
        post:
            summary: Update business email
            description: Endpoint to update the email of a business.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UpdateEmailRequest"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UpdateEmailResponse"
    /business/delete:
        delete:
            summary: Delete business
            description: Endpoint to delete a business.
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/DeleteBusinessResponse"
    /business/update:
        post:
            summary: Update business
            description: Endpoint to update a business.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UpdateBusinessRequest"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UpdateBusinessResponse"
    /business/logout:
        get:
            summary: Logout business
            description: Endpoint to logout a business.
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/LogoutResponse"
    /business/logoutall:
        get:
            summary: Logout all businesses
            description: Endpoint to logout all businesses.
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/LogoutAllResponse"
components:
    schemas:
        BusinessSignupRequest:
            type: object
            properties:
                name:
                    type: string
                email:
                    type: string
                country:
                    type: string
                address:
                    type: string
                city:
                    type: string
                state:
                    type: string
                postalCode:
                    type: string
                website:
                    type: string
                description:
                    type: string
                tier:
                    type: string
                industry:
                    type: string
        BusinessSignupResponse:
            type: object
            properties: // Add properties and their types here
        BusinessProfileResponse:
            type: object
            properties: // Add properties and their types here
        UpdatePasswordRequest:
            type: object
            properties: // Add properties and their types here
        UpdatePasswordResponse:
            type: object
            properties: // Add properties and their types here
        VerifyPasswordRequest:
            type: object
            properties: // Add properties and their types here
        VerifyPasswordResponse:
            type: object
            properties: // Add properties and their types here
        UpdateEmailRequest:
            type: object
            properties: // Add properties and their types here
        UpdateEmailResponse:
            type: object
            properties: // Add properties and their types here
        DeleteBusinessResponse:
            type: object
            properties: // Add properties and their types here
        UpdateBusinessRequest:
            type: object
            properties: // Add properties and their types here
        UpdateBusinessResponse:
            type: object
            properties: // Add properties and their types here
        LogoutResponse:
            type: object
            properties: // Add properties and their types here
        LogoutAllResponse:
            type: object
            properties: // Add properties and their types here
